name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Choose your Python version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build and deploy
        run: |
          # Build your Brython code here, if needed
          python .github/workflows/your_script.py
          # Deploy to GitHub Pages
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
